server:
  port: 8082

spring:
  application:
    name: order-validation

redis:
  hostname:  redis-14149.c258.us-east-1-4.ec2.cloud.redislabs.com
  port: 14149
  username: Phelim
  password : PTAgcoep25rghJlVAp7co1zOs6mZS3vo
